# Generated by Django 4.1.1 on 2022-09-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bath Oil', 'Bath Oil'), ('Massage Oil', 'Massage Oil'), ('Steam Inhalation', 'Steam Inalation'), ('Diffuser', 'Diffuser'), ('Fragrance', 'Fragrance'), ('Shower', 'Shower'), ('Foot Bath', 'Foot Bath'), ('Compress', 'Compress'), ('Mouthwash', 'Mouthwash'), ('Ointment', 'Ointment')], max_length=30)),
            ],
        ),
    ]
