# Generated by Django 4.1.1 on 2022-09-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EoBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('essential_oil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='benefits', to='essentials.essential')),
            ],
        ),
    ]
