# Generated by Django 4.1.1 on 2022-09-09 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_user', to=settings.AUTH_USER_MODEL)),
                ('tested_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_recipes', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_user', to=settings.AUTH_USER_MODEL)),
                ('bookmarked_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_recipes', to='recipes.recipe')),
            ],
        ),
    ]
