# Generated by Django 4.1.1 on 2022-09-10 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('jwt_auth', '0002_testedrecipe_bookmarkedrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkedrecipe',
            name='bookmarked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmarkedrecipe',
            name='bookmarked_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_recipes_list', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='testedrecipe',
            name='tested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testedrecipe',
            name='tested_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tested_recipes_list', to='recipes.recipe'),
        ),
    ]
