# Generated by Django 4.1.1 on 2022-09-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('the_base_oil', models.TextField(max_length=400)),
                ('safe_usage', models.TextField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BoBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('base_oil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='benefits', to='bases.baseoil')),
            ],
        ),
    ]
