# Generated by Django 4.1.1 on 2022-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('the_base_oil', models.TextField(max_length=400)),
                ('safe_usage', models.TextField(max_length=250)),
            ],
        ),
    ]
