# Generated by Django 4.1.1 on 2022-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseoil',
            name='image',
            field=models.CharField(default='tbc', max_length=100),
        ),
    ]
