# Generated by Django 4.1.1 on 2022-09-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseoil',
            name='safe_usage',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
