# Generated by Django 4.1.1 on 2022-09-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0002_remedy_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedy',
            name='name',
            field=models.CharField(choices=[('Pampering & Beauty', 'Pampering & Beauty'), ('Digestive Problems', 'Digestive Problems'), ('Respiratory Complaints', 'Respiratory Complaints'), ('Circulatory Problems', 'Circulatory Problems'), ('Aches & pains', 'Aches & Pains'), ('Skin Care', 'Skin Care'), ('Mind & Wellbeing', 'Mind & Wellbeing'), ("Women's Health", "Women's Health"), ('First Aid', 'First Aid'), ('Hair Care', 'Hair Care')], max_length=30),
        ),
    ]
