# Generated by Django 4.1.1 on 2022-09-09 10:59

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='OtherIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('makes', models.TextField(blank=True, max_length=100)),
                ('step_one', models.TextField(max_length=500)),
                ('step_two', models.TextField(blank=True, max_length=500)),
                ('step_three', models.TextField(blank=True, max_length=500)),
                ('safe_usage', models.TextField(max_length=250)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherIngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('other_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.otheringredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_ingredient_amount', to='recipes.recipe')),
            ],
        ),
    ]
