# Generated by Django 4.1.1 on 2022-09-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('essentials', '0001_initial'),
        ('bases', '0001_initial'),
        ('remedies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('makes', models.TextField(blank=True, max_length=100)),
                ('step_one', models.TextField(max_length=500)),
                ('step_two', models.TextField(blank=True, max_length=500)),
                ('step_three', models.TextField(blank=True, max_length=500)),
                ('safe_usage', models.TextField(blank=True, max_length=250)),
                ('public', models.BooleanField(default=True)),
                ('applications', models.ManyToManyField(blank=True, related_name='recipes', to='applications.application')),
                ('remedies', models.ManyToManyField(blank=True, related_name='recipes', to='remedies.remedy')),
            ],
        ),
        migrations.CreateModel(
            name='OtherIngredientAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('measurement', models.CharField(max_length=20)),
                ('other_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.otheringredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_ingredient_amount', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='EssentialOilAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('measurement', models.CharField(max_length=20)),
                ('essential_oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='essentials.essential')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essential_oil_amount', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='BaseOilAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('measurement', models.CharField(max_length=20)),
                ('base_oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='bases.baseoil')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_oil_amount', to='recipes.recipe')),
            ],
        ),
    ]
