# Generated by Django 4.1.1 on 2022-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0001_initial'),
        ('applications', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='applications.application'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='remedies',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='remedies.remedy'),
        ),
    ]
