# Generated by Django 4.1.1 on 2022-09-09 14:34

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseoilamount',
            name='amount',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={'measurement': '', 'quantity': ''}, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='safe_usage',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
