# Generated by Django 4.1.1 on 2022-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Balancing', 'Balancing'), ('Cleansing', 'Cleansing'), ('Energising', 'Energising'), ('Relaxing', 'Relaxing'), ('Uplifting', 'Uplifting')], max_length=10)),
            ],
        ),
    ]
