# Generated by Django 4.1.1 on 2022-09-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('key_actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('method_of_extraction', models.CharField(max_length=250)),
                ('description_short', models.TextField(max_length=250)),
                ('description_long', models.TextField(max_length=800)),
                ('the_essential_oil', models.TextField(max_length=400)),
                ('the_plant', models.TextField(max_length=400)),
                ('safe_usage', models.TextField(max_length=250)),
                ('image', models.CharField(max_length=100)),
                ('key_actions', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='essentials', to='key_actions.key_action')),
            ],
        ),
    ]
