# Generated by Django 4.1.1 on 2022-09-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('remedies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Balancing', 'Balancing'), ('Cleansing', 'Cleansing'), ('Energising', 'Energising'), ('Relaxing', 'Relaxing'), ('Uplifting', 'Uplifting')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Essential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('method_of_extraction', models.CharField(max_length=250)),
                ('description_short', models.TextField(max_length=250)),
                ('description_long', models.TextField(max_length=800)),
                ('the_essential_oil', models.TextField(max_length=400)),
                ('the_plant', models.TextField(max_length=400)),
                ('safe_usage', models.TextField(max_length=250)),
                ('image', models.CharField(max_length=100)),
                ('applications', models.ManyToManyField(blank=True, related_name='essential_oils', to='applications.application')),
                ('blends_well_with', models.ManyToManyField(blank=True, to='essentials.essential')),
                ('key_action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='essential_oils', to='essentials.keyaction')),
                ('remedies', models.ManyToManyField(blank=True, related_name='essential_oils', to='remedies.remedy')),
            ],
        ),
        migrations.CreateModel(
            name='EoUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('essential_oil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uses', to='essentials.essential')),
            ],
        ),
        migrations.CreateModel(
            name='EoBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('essential_oil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='benefits', to='essentials.essential')),
            ],
        ),
    ]
