# Generated by Django 4.1.1 on 2022-09-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('key_actions', '0001_initial'),
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential',
            name='key_actions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='essential_oils', to='key_actions.key_action'),
        ),
    ]
