# Generated by Django 4.1.1 on 2022-09-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential',
            name='the_plant',
            field=models.TextField(max_length=500),
        ),
    ]
