# Generated by Django 4.1.1 on 2022-09-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0001_initial'),
        ('applications', '0001_initial'),
        ('essentials', '0002_alter_essential_key_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential',
            name='applications',
            field=models.ManyToManyField(related_name='essential_oils', to='applications.application'),
        ),
        migrations.AddField(
            model_name='essential',
            name='remedies',
            field=models.ManyToManyField(related_name='essential_oils', to='remedies.remedy'),
        ),
    ]
