# Generated by Django 4.1.1 on 2022-09-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('remedies', '0001_initial'),
        ('essentials', '0003_essential_applications_essential_remedies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='essential_oils', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='essential',
            name='remedies',
            field=models.ManyToManyField(blank=True, related_name='essential_oils', to='remedies.remedy'),
        ),
    ]
