# Generated by Django 4.1.1 on 2022-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essentials', '0004_alter_essential_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essential',
            name='blends_well_with',
            field=models.ManyToManyField(blank=True, to='essentials.essential'),
        ),
    ]
